### ISSUE TITLE
[Feature request]: Allow administrators to assign bookings to non-registered members.

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1009]
### Is your feature request related to a problem? Please describe?

The University Film Program needs to manage equipment bookings by assigning custody to students without granting them access to view or book the inventory themselves, while maintaining detailed contact information for tracking and communication purposes, and ensuring that the administrator can handle reminders manually.

### Describe the solution you'd like

Let me select a NRM on the booking custody field.

**Comment by DonKoko** [comment]
Our DB and Code is mostly ready for this, will require minor adjustments for it to work:
1. Adjust custodian selector for bookings. Show NRMs there as well and adjust how its value is handled and send to the server
2. There is some small code changes we need to do in upsertBooking as there is 1 case that needs handling. It was very easy when i tested it, i think if we get there we will see it and solve it directly
3. Check all functionality that sends meails related to booking. We have to make sure it checks specifically that the booking is attached to a user rather than teamMember and only then send email.(for the custodian. admin should receive emails anyways)

**Comment by DonKoko** [comment]
This is done and released.
