### ISSUE TITLE
[Feature request]: Add Description field when configuring bookings

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1081]
### Is your feature request related to a problem? Please describe?

A couple of users are in need of a way to attach a bit of extra information to a booking. They want to be able to see this information in the booking index and calendar.

### Describe the solution you'd like

- [x] Add a Description field when configuring booking
- [x] Add a Description column in booking index
- [x] When hovering over a booking entry in Calendar overview a pop-over with more information appears

**Creating a booking with a description**
https://www.figma.com/design/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?node-id=6658-21268

Additional input:

- Owner / Admin users can edit Description fields at any time
- Self-service users can edit Description field at any time

**Comment by carlosvirreira** [comment]
One of our users / requesters took the time to make some visualizations (not final just examples). 

![booking edit](https://github.com/Shelf-nu/shelf.nu/assets/12449255/930fd0d1-963c-449f-bee6-0bba17f9bf6f)
![new booking](https://github.com/Shelf-nu/shelf.nu/assets/12449255/5905bfa7-2581-4235-9acf-0a3acb223fb0)

**Comment by carlosvirreira** [comment]
<img width="879" alt="Screenshot 2024-06-26 at 13 49 49" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/ac1e3db1-608f-4731-8e39-8752f9fc01b6">

**Comment by carlosvirreira** [comment]
Assigning you @DonKoko to just get a Quick Opinion.

**Comment by DonKoko** [comment]
Hmm I am not convinced by this. I would understand the idea of adding a textarea field where they can put more info, or notes area or something, but this seems like just adding another name field. If that's all that is needed, why cant this data be added to the name?

**Comment by carlosvirreira** [comment]
@DonKoko context provided

"The calendar question was that if it would be possible to add notes or tags or colour code to the bookings in the calendar so i can identify the bookings better straight from the calendar view. Workaround is to put the description directly into the booking name but then it is also shown in the pdf checklist and that we want to use as a custody agreement with the client on check-out. "

**Comment by mattlamb99** [comment]
+1 Would like notes on bookings. Generic textarea.  We would use this for example:

- 'Remember to pack extra batteries, this is a long event'
- 'Please don't drive on the grass when you deliever this booking'
- 'Client happy to swap the Wireless Microphone booked for a Wired Microphone if the other event needs it'


I could also see a use for generic 'tagging' for bookings too, but thats another topic.

**Comment by DonKoko** [comment]
hey @mattlamb99. Thanks a lot for your input. We are considering a way to approach it to make it not just a patch but a good long/term solution. Keep track of this issue to stay updated.

**Comment by DonKoko** [comment]
@jurrejansen I think this is becoming quite important. It also got mentioned yesterday in our call. Could you please take an hour thinking about this. Here are some points I was thinking about:
- Option 1: We just add a notes field(basically like a description field). Simple but very limited
- Option 2: We implement the notes concept from Assets and attach it also to bookings
- How do we display a preview of the notes? We can show it easily on the bookings index but what about the calendar? Maybe we can show it when you click and entry
- I think in either cases this should not be part of the modal on crate, the field should only be visible on the actual booking page.

Would love to hear what you think.

**Comment by jurrejansen** [comment]
Hi @DonKoko 

@carlosvirreira  and I have discussed this and I have some WIP designs to share. Option 1 seems most important and would directly address the user input we've gotten.

This would involve
- Adding a Description field
- Adding a Description column to the booking index
- A way to read the description in Calendar view
- Add description to the automated mails

In WIP scenario below I'm covering most of these points. But there will probably be some cases to cover after initial feedback.

**Creating a booking with description**
https://www.figma.com/design/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?node-id=6658-21268

Also explored the option of introducing the Activity tab to bookings. And during initial configuration the Description field (would've been named differently) would have created a comment in Activity tab that would be pinned automatically. The pinned comment (only 1 pinned comment at once) would then show when hovering in Calendar view etc.

However, we decided not do this because it would introduce limitations and we want to differentiate the Description and a pinned comment. A WIP scenario for Booking Activity tab and pinning comments below. Suggestion would be to icebox this and log into another issue. And for now focus basically on Option 1.

**Inspecting the Activbity tab on a booking page and pinning comments** 
https://www.figma.com/design/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?node-id=6736-23135

**Comment by DonKoko** [comment]
@jurrejansen @carlosvirreira lovely, I like it. No specific feedback right now. 
I think we should drop the activity tab idea for now. The description should be good enough. 

@jurrejansen can you please update the original issue comment with the designs and description and I will add this to roadmap as planned and get someone to work on it.

**Comment by DonKoko** [comment]
@jurrejansen this can be implemented. Can you please remove from the flow the pages that show the tabs for a booking. We leave that for the future

**Comment by jurrejansen** [comment]
@DonKoko I noticed if there are warning labels they're shown in between Description and From column. I would expect the warning labels to always show: Right side of Name, Status column and stuck left of the first column that comes next
![Screenshot 2024-07-23 at 16 35 46](https://github.com/user-attachments/assets/9d7c025a-75ae-48be-87fe-82d3bcfbbfb8)

**Comment by DonKoko** [comment]
hey @jurrejansen. I have adjusted the order of the columns. Thanks for the feedback
