### ISSUE TITLE
[Feature request]: Direct link to team workspace

### ISSUE THREAD

**Issue by DroneProf** [Shelf-nu/shelf.nu#1084]
### Contact Details

rose196@purdue.edu

### Is your feature request related to a problem? Please describe?

I plan to link to the shelf app from another "main" website that my users initially interface with. The users log into shelf and default to their personal workspace instead of the team workspace.

### Describe the solution you'd like

Ideally provide a direct link to a team workspace. Secondarily, provide a way for users to set default workspace in settings.

**Comment by DonKoko** [comment]
hey @DroneProf. Thanks for the request.
So currently what we have planned is to simply save the last workspace you were in, so every time you login it will be remembered. So that means you only need to change it the first time you are logged in. 

Do you think that is sufficient and would it solve your use case?

**Comment by DroneProf** [comment]
Hey @DonKoko ! That fix works perfectly. I think last active makes the most sense for the application. Many thanks!

**Comment by DonKoko** [comment]
@DroneProf my pleasure. Feel free to open an issue if there is something else.
