### ISSUE TITLE
[Feature request]: Bulk tagging

### ISSUE THREAD

**Issue by swantzter** [Shelf-nu/shelf.nu#1208]
### Contact Details

replies to this issue will notify me by email

### Is your feature request related to a problem? Please describe?

I recently updated my tagging strategy for assets and wanted to add some of my new tags to 20+ devices

### Describe the solution you'd like

On the assets page, I'd like to see an "add tag(s)" and "remove tag(s)" option in the actions menu when I have multiple assets selected

**Comment by DonKoko** [comment]
hey @swantzter , thanks for the feature request.

Making a bulk action for "add tags" should be pretty straight forward, however I am a bit skeptical of removing tags. We would need to design a process around it because we could only remove tags that all items share for example.
The only option that is would be straight forward for removing tags is having an action "Remove all tags" that will basically remove all tags from the selected items, however I feel this would be a very rare use case.

**Comment by swantzter** [comment]
@DonKoko fair enough, bulk add would be the priority of this for me, however for bulk remove I'd suggest the simplest approach would be a "remove tag(s) X from all these assets, if they have that tag, if they don't, do nothing with that asset"

**Comment by DonKoko** [comment]
I like that approach. We will discuss this internally and see for when/how we can plan it. I dont see it as a major complex feature so it could be in the near future.

**Comment by carlosvirreira** [comment]
hi @swantzter this is live!
