### ISSUE TITLE
[Improvement request]: Optimize thumbnail images used in some indexes and Asset page

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#1216]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

Frequently I open an index page like Assets, Kits or Locations and it takes a second before thumbnails are loaded. Not a huge deal but I notice it a lot. Thumbnail images are displayed at 48x48 so the version of the uploaded image that is used there could be very little kbs.

The video doesn't really convey what I mean because most of the time I actually see the HTML placeholder for an image there for a while if you know what I mean.

https://github.com/user-attachments/assets/5f3c8b2e-419b-44fb-afd5-4b60b9442309

### Describe the solution you'd like

Compress / optimize thumbnail images used in indexes (Assets, Kits, Locations) and Asset page.

**Comment by DonKoko** [comment]
@jurrejansen good initiative but that is not caused by network connection or performance, but rather that those images are private, and if they key stored is expired, they cannot be rendered. So we have to generate a new key and then they show up. 

That being said, I still think we can handle this better and make it look nicer. I am open to suggestions for having a nice fallback in this case, maybe something indicating the image is "loading"

**Comment by jurrejansen** [comment]
@DonKoko Oh I see. Well perhaps the placeholder that is used for entries that have no image can also be used as a placeholder / fallback while image is loading. Just to avoid the HTML fallback thing.

![Screenshot 2024-07-29 at 14 24 21](https://github.com/user-attachments/assets/10db282f-d759-4087-94fa-26bb826704f6)

![Screenshot 2024-07-29 at 14 21 15](https://github.com/user-attachments/assets/ab3e8af6-1e99-426a-94c3-29ae1ed7e840)
