### ISSUE TITLE
Mobile enhancement: Log out action hard to achieve on Safari

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#122]
Capture from my phone > Safari > Incognito

![IMG_2684](https://github.com/Shelf-nu/shelf.nu/assets/12449255/e62610bd-9da4-4a56-92d1-9fee19e735fa)

You have to scroll down and get some Jank before you get to see the icon to log out.

**Comment by carlosvirreira** [comment]
https://github.com/Shelf-nu/shelf.nu/assets/12449255/18876451-8e44-4996-84bc-5dd00d688c41

Additionally, the 'settings' route seems to behave differently than categories, etc. Would be nice to make them work similarly.

**Comment by DonKoko** [comment]
> Additionally, the 'settings' route seems to behave differently than categories, etc. Would be nice to make them work similarly.

It was because of the link on the user icon. Thats fixed now.


> You have to scroll down and get some Jank before you get to see the icon to log out.

This is really complicated to fix and requires some custom js and some strange fixes. I am leaving it as debt to solve it at a later stage when we have MVP ready.
Resources:
- https://gist.github.com/klich3/d6a0a04793e6f563dd138fa5308aa69d
- https://stackoverflow.com/a/70848686/3793913

**Comment by jurrejansen** [comment]
Closing, should be solved by moving some menu items / actions behind in the dropdown when clicking profile

https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=627-136769&mode=design
