### ISSUE TITLE
[Improvement]: Adding Assets in Bookings performance

### ISSUE THREAD

**Issue by McMurdo42** [Shelf-nu/shelf.nu#1240]
### Contact Details

real.davidcoleman@gmail.com

### What happened?

When searching to add assets to a booking the search is extremely slow.

### What is the expected behaviour?

The search should be as fast as the search on the asset page. It would also be helpful if you could add assets to a booking from the asset page since that page provides more relevant information. Currently you can only create a new booking from the asset page.

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome

**Comment by carlosvirreira** [comment]
@McMurdo42 "It would also be helpful if you could add assets to a booking from the asset page since that page provides more relevant information." 

This is a good idea. Thank you for taking the time to share it!

**Comment by DonKoko** [comment]
hey @McMurdo42 . Thanks for the feedback and suggestion.
I have changed this issue from "Bug" to "Improvement" so its labeled correctly as a task to improve performance of adding assets.

I also created a separate issue for your other suggestion: https://github.com/Shelf-nu/shelf.nu/issues/1245

**Comment by DonKoko** [comment]
hey @McMurdo42. I have been looking into the performance issue you reported. Based on my expectations as well as me testing it now, I get the opposite results of what you are mentioning. Assets index is like 20% slower than booking/add-assets because it loads more data and has some more complex queries.

Could you maybe provide me with some more info about your test case and when you are getting this performance issue?

**Comment by DonKoko** [comment]
I have made some changes to improve the performance. Closing this issue for now. Will be picked up later with a more general performance improvements.
