### ISSUE TITLE
[Bug]: Team Archived Bookings

### ISSUE THREAD

**Issue by McMurdo42** [Shelf-nu/shelf.nu#1253]
### Contact Details

real.davidcoleman@gmail.com

### What happened?

Going to the team page.
Select a user
view their bookings
filter by archived

Gives you a oops something went wrong
Trace id: eimjdp4zfbwjiskdivsquzlm

### What is the expected behaviour?

Should just show you archived bookings for that user. Would be nice to on the user page see all bookings including archived but leave them hidden on the bookings page.

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome

**Comment by DonKoko** [comment]
Hey @McMurdo42 . We have seen already the error you faced and I am working on solving it right now. Thanks for reporting.

**Comment by DonKoko** [comment]
hey @McMurdo42 . The issue is fixed and is being release. Will be live once this action finishes: https://github.com/Shelf-nu/shelf.nu/actions/runs/10406462525

We also discussed it with Carlos and we thought your suggestion to show the archived bookings on the user bookings page is good so we went ahead and changed that.

Please let us know if you face any further issues. We really appreciate your input.
