### ISSUE TITLE
feat: advanced view of asset index

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#1322]
After many considerations we decided that instead of making the default view of the asset index too crowded, we will instead create an advanced view for advanced users.

Designs: https://www.figma.com/design/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?node-id=7109-18468&node-type=canvas&t=deekb5gz94eEw1Zt-0

Checklist:

- [x] Make sure when custom fields are updated, we update the `columns` inside `AssetIndexSettings`
- [x] When a user creates a new Organization - create the settings object
- [x] ~When a new `UserOrganization` is created, we need to create the `AssetIndexSettings` - check this: `createUserOrgAssociation`~ - decided on a different and simpler approach. Inside `getAssetIndexSettings`, if not settings are found we just create them on the go. This basically handles multiple cases and will make sure there is never a user without settings.
- [x] When a user is created create the `AssetIndexSettings` for their personal org
- [x] Add image option in first column
- [x] Allow to freeze name column
- [x] Make header sticky
- [x] ScrollToTop button
- [ ] `Possibility to open asset in new tab`
- [x] Add the "disabled on mobile thing"
- [x] Double check if simple mode didnt get any bugs related to other changes
- [x] Switching between modes should keep each mode's own filters
- [x] UI still needs reworking. Sent a lot of time on sticky header but it might have been a mistake. We should make the table always be 100vh and scrollable inside, that way we dont need to worry about making anything sticky. Supabase UI is a good example for this.
- [x] AssetViewSearch wont be used in this advanced index so we need to update the search field. For now the search field will search in `asset.title` and `asset.description`
- [x] Columns to still add: `available for bookings`
- [x] sorting options - name should always be first
- [x] add "clear all" for sorts
- [x] Should we allow AdvancedAssetIndex for `Base` and `Self_service` users?
- [x] add `qrId` column
- [x] Disable apply filters if there are any errors in schema
- [x] Fix components file structure. Its a bit of  a mess now.  Everything related to advanced should be moved to advanced folder and organized better
- [x] Export to csv
- [x] Because of how we manage filters by automatically building the object from the search params, we need to create some type of safety measure that only considers real fields, so if someone just adds a random param such as `?name=is:xxx` we dont parse this as it will cause for nothing to be shown and such errors:
```
{"level":50,"time":1729247131694,"pid":781325,"hostname":"DESKTOP-4O50AD2","err":{"cause":{"name":"PrismaClientKnownRequestError","code":"P2010","clientVersion":"5.15.1","meta":{"code":"42703","message":"column a.name does not exist"},"stack":"PrismaClientKnownRequestError: \nInvalid `prisma.$queryRaw()` invocation:\n\n\nRaw query failed. Code: `42703`. Message: `column a.name does not exist`\n 
```
- [x] For relation filters such as Kit, Location and Category, when the operator is either `is` or `isNot` we can actually use a select instead of the text field. This will be way better UX.
- [x] Types need to be reviewed and fixed. We dont have a specific type for items returned from the AdvancedAssetIndex. This should be added.
- [x] For some reason the model-filters gets re-validated when the asset index re-validates. This should for sure not be happening on advanced index:
![Image](https://github.com/user-attachments/assets/f30abd91-9602-4f08-9a04-9d7734f5518a)
- [x] Relationship column values should be links to the entries: Location, Kit
- [x] For each field type, implement an operator that can act as a logical OR. 
- [x] Make sure each filter can be added just once
- [x] Make sure each Sort can be added just once
- [x] Make scroll to top work with the updated index UI
- [x] fix tags filter
- [x] re-ordering columns is broken again
- [x] When assets are imported from a CSV, the custom fields columns get the wrong type in the columns jsonb inside `AssetIndexSettings`. They are all parsed as 'single-line text'
- [x] Change the BG color of the header
- [x] Fix pagination styling - make it more compact
- [x] Weird scrollbar areas are now showing up. I am not sure what caused this, our scrollbars were looking nice, now they are not anymore. THis happens everywhere where we have overflow-scroll
- [x] Make sure that `page` param is removed when the filters change.
- [x] ~Text fragment~ - this doesnt really work like I expected. It cannot do partial match and it only works on chromium browsers even tho caniuse says something else
- [ ] How do we change error handling so we dont block UI when there are errors
- [x] `submitOnEnter` got broken because of the validations. We need to figure out what is going on and restore it after release
- [ ] We need to do some extra checks to make sure the searchParams values are valid and if they are not reset them. So we have for example this case: `http://localhost:3000/assets?per_page=20&status=IN_CUSTODY`. In this case `status` is a valid key but the value is not valid based on the schema we use for searchParams in the advanced index. This needs to be handled properly.
- [x] number field validation is not working as expected

Pre-release checklist:
- [x] Fix migration we are not using related to filters
- [x] Fix all TODOs

<details>

<summary>Sorting options tests: ✅</summary>

 - [x] Name
 - [x] id
 - [x] status
 - [x] createdAt
 - [x] value
 - [x] description
 - [x] category
 - [x] location
 - [x] kit
 - [x] custody
 - [x] custom field - text
 - [x] custom field -multiline text
 - [x] custom field - boolean
 - [x] custom field - options
 - [x] custom field  - date

</details>

<details>

<summary>Filtering search params tests:✅</summary>

## String Fields (id, name, category, location, kit, custody)
- [x] `?name=is:John`
- [x] `?name=isNot:John`
- [x] `?name=contains:oh`
- [x] `?category=is:Electronics`
- [x] `?location=contains:New York`

## Text Fields (description)
- [x] `?description=contains:important`

## Boolean Fields (availableToBook)
- [x] `?availableToBook=is:true`
- [x] `?availableToBook=is:false`

## Date Fields (createdAt)
- [x] `?createdAt=is:2023-05-15`
- [x] `?createdAt=isNot:2023-05-15`
- [x] `?createdAt=before:2023-05-15`
- [x] `?createdAt=after:2023-05-15`
- [x] `?createdAt=between:2023-05-01,2023-05-31`

## Number Fields (valuation)
- [x] `?valuation=is:1000`
- [x] `?valuation=isNot:1000`
- [x] `?valuation=gt:1000`
- [x] `?valuation=lt:1000`
- [x] `?valuation=gte:1000`
- [x] `?valuation=lte:1000`
- [x] `?valuation=between:1000,2000`

## Enum Fields (status)
- [x] `?status=is:AVAILABLE`
- [x] `?status=isNot:AVAILABLE`

## Array Fields (tags)
- [x] `?tags=contains:urgent`
- [x] `?tags=containsAll:urgent,important`
- [x] `?tags=containsAny:urgent,important`

### Single Line Text
- [x] `?cf_fieldName=is:Value`
- [x] `?cf_fieldName=isNot:Value`
- [x] `?cf_fieldName=contains:alue`

### Multiline Text
- [x] `?cf_fieldName=contains:important information`

### Boolean
- [x] `?cf_fieldName=is:true`
- [x] `?cf_fieldName=is:false`

### Date
- [x] `?cf_fieldName=is:2023-05-15`
- [x] `?cf_fieldName=isNot:2023-05-15`
- [x] `?cf_fieldName=before:2023-05-15`
- [x] `?cf_fieldName=after:2023-05-15`
- [x] `?cf_fieldName=between:2023-05-01,2023-05-31`

### Option (Enum)
- [x] `?cf_fieldName=is:Option1`
- [x] `?cf_fieldName=isNot:Option1`

## Multiple Filters
- [x] `?name=contains:John&status=is:AVAILABLE&valuation=between:1000,2000&cf_customField=is:true`

</details>

### Custom field filtering testing

- [x] single line
- [x] multi line
- [x] boolean
- [x] options
- [x] date

**Comment by carlosvirreira** [comment]
Few small points from testing. 

- [ ] Let's make our asset name look similar than on simple view. ![Image](https://github.com/user-attachments/assets/bf0f8144-0d28-4480-aa59-f04fe2de4f75) - (font-medium)

- [ ] Rendering of description is different when a description is short. Ideally they look similar on advanced view. In the case of having too many characters we put an ellipsis on the end of the available to render text space. But it looks like it takes less width than the other case. ![Image](https://github.com/user-attachments/assets/ac90b7b9-ac0f-41e0-80f3-659995bd7314)

**Comment by DonKoko** [comment]
@carlosvirreira I am deploying a version of this to staging that would benefit from testing. So here is what you can currently test:

Column configuration:
- [ ] Enable/disable columns
- [ ] re-order columns - both default and cf columns

Index configuration:
- [ ] changing between simple and advanced index
- [ ] freezing/unfreezing first column
- [ ] show/hide asset image

Sorting:
- [ ] changing sorting order and making sure results are correct
- [ ] testing based on different sorting field type:
- [ ]  Name
- [ ] id
- [ ] status
- [ ] createdAt
- [ ] value
- [ ] available to book
- [ ] description
- [ ] category
- [ ] location
- [ ] kit
- [ ] custody
- [ ] custom field - text
- [ ] custom field -multiline text
- [ ] custom field - boolean
- [ ] custom field - options
- [ ] custom field - date

**Comment by carlosvirreira** [comment]
> @carlosvirreira I am deploying a version of this to staging that would benefit from testing. So here is what you can currently test:
> 
> Column configuration:
> 
> * [ ]  Enable/disable columns
Safari - Desktop:

https://github.com/user-attachments/assets/5eb5ee22-dce1-4ddf-a680-6ff05ca9d934

Chrome - Desktop: 

Same behaviour

> * [ ]  re-order columns - both default and cf columns

Safari / Chrome: 

After moving a column it snaps back to its original position. 


https://github.com/user-attachments/assets/dd0f441a-dd91-44ba-9151-969c2beb96e9

> 
> Index configuration:
> 
> * [ ]  changing between simple and advanced index

Works well. 

> * [ ]  freezing/unfreezing first column

Works well. 

> * [ ]  show/hide asset image

Works well. 'Remembers' the preference.
> 


> Sorting:
> 
> * [ ]  changing sorting order and making sure results are correct
> * [ ]  testing based on different sorting field type:
> * [ ]   Name

Ascending > Check
Descending > Check

Observation: We might need to do a explainer page/knowledgebase article for how sorting logic works for ascending descending.

> * [ ]  id

Ascending > Check
Descending > Check

> * [ ]  status

Ascending > Check
Descending > Check

Observation: Unavailable to book seems to not have any sort of extra weight on the sort. So it appears in random position. This is not an issue but it is worth mentioning that it might cause some sort of a feeling with our users sorting. Not sure how to handle this for now.

> * [ ]  createdAt

Ascending > Check
Descending > Check

> * [ ]  value

Ascending > Fail
Descending > Fail

Cannot state that this works due to the fact that Value is toggled off by default on my test and I cannot enable it without snapping back to its original state.

> * [ ]  available to book

Ascending > Fail
Descending > Fail

In both directions the values are inconsistent.

![Screenshot 2024-10-17 at 11 25 45](https://github.com/user-attachments/assets/cf0bd0be-3a64-4dd5-ae12-7dc255ad6a84)


> * [ ]  description

Ascending  > Check
Descending > Fail

Ascending: Numbers come first (matches our expectation), then uppercase 'A' to 'Z', then lowercase 'a' to 'z'.
Descending: Lowercase 'z' to 'a', then uppercase 'Z' to 'A', then numbers (contradicts our expectation).

> * [ ]  category

Ascending  > Check
Descending > Check

> * [ ]  location

Ascending > Fail
Descending > Fail

Cannot state that this works due to the fact that Value is toggled off by default on my test and I cannot enable it without snapping back to its original state.

> * [ ]  kit

Ascending > Check
Descending > Check

sorting is consistent with ASCII/Unicode character ordering, where:

Numbers (0-9) come first
Then uppercase letters (A-Z)
Then lowercase letters (a-z)

However, it might not be the most human friendly. 

A more natural sorting method might:

Ignore case (treat uppercase and lowercase the same)
Sort numbers as whole values rather than character-by-character
Place purely alphabetic entries before alphanumeric ones

In such a "natural" sort, the order might be:

KIT TEST
z0101
00 Kit

> * [ ]  custody

Ascending > Check
Descending > Check

Same observation on human friendly. It follows Ascii/Unicode but might be confusing.

> * [ ]  custom field - text

Ascending > Check
Descending > Check

Same observation on human friendly. It follows Ascii/Unicode but might be confusing.

> * [ ]  custom field -multiline text
> * [ ]  custom field - boolean
> * [ ]  custom field - options
> * [ ]  custom field - date


Other observation:

> Sometimes I feel like it could be nice to apply the sorting if you remove a sorting rule line. However, I can see why someone might want to click on the apply sorting button. Worth to discuss shortly.
> Assigning custody via Actions returns an unexpected error
