### ISSUE TITLE
[Feature request]: Mass mark assets as unbookable/bookable via batch actions

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1331]
### Is your feature request related to a problem? Please describe?

I have applied a tag called 'Broken' to around 30 pieces of equipment. I want to make sure nobody books them or reserves them. 

I have to open 30 asset pages, and mark them 1 by one. 

### Describe the solution you'd like

Ideally just as the other batch actions I can perform this change in mass.

**Comment by DonKoko** [comment]
How it should work:

Actions dropdown gets 2 new options
 - Mark as unavailable
 - Mark as available
 
 When you select either option, you are prompted with a window to confirm.
 
Here I want to try a different approach. Instead of doing some complex validations what can and what cant be marked as unavailable, lets simply do it in such a way:
1. Both actions are enabled, no matter the selection
2. When an action is triggered, it gets applied only to the relevant assets. So if we mark as unavailable and 10 out of the 12 assets are available, it will only apply tho those 10.


@hunar1312 let me know if there are any questions.
