### ISSUE TITLE
[Feature request]: Scan codes from inside the website/web application

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#309]
### Contact Details

carlos@shelf.nu

### Is your feature request related to a problem? Please describe?

When I added shelf to my Home Screen as an 'web app' (https://support.apple.com/en-gb/guide/iphone/iph42ab2f3a7/ios) 

I now have to open my camera app all the time to start scanning codes. 

I would like to do this in the mobile version of the website.

This issue is in progress, a bounty will be placed for it later.

### Describe the solution you'd like

<img width="495" alt="Screenshot 2023-08-22 at 13 28 07" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/73391226-8949-45aa-ab14-fc07aa9ce8e0">

**Comment by jurrejansen** [comment]
@carlosvirreira let's change this placement of button to the top navigation so it is always visible.

We'll have to discuss what the button it actually going to do
- Open default Camera App
- Design/Develop MVP scanner

**Comment by carlosvirreira** [comment]
Let's go for > Open default Camera App

**Comment by jurrejansen** [comment]
It would be great if it could work like this:

OPTION 1

- Tap 'Scan' icon
- Opens Default Camera app within the PWA
- Scan code
- Redirects to asset page

Instead of:

OPTION 2

- Tap 'Scan' icon
- Opens Default Camera App
- switches from browser app to Default Camera app
- Scan code
- Switches to browser app and opens new tab with asset page

With the first option having a kind of UX like this, but with scanning capability

https://github.com/Shelf-nu/shelf.nu/assets/76112272/cd80f75d-f4a9-41f6-a25e-de930188e31d

But if we want to keep it simple, let it be a fast improvement and open a bounty for it, the second option may be better

@DonKoko thoughts?

**Comment by DonKoko** [comment]
I dont know for sure but I am pretty certain that option 1 is not possible.

**Comment by carlosvirreira** [comment]
Example website opening camera in - website


https://github.com/Shelf-nu/shelf.nu/assets/12449255/b31d4432-2f27-46e0-9307-d17ff94661db

**Comment by carlosvirreira** [comment]
@ap172x I see you are attempting this. Perhaps it is handy for you to join us on Discord? 

https://discord.gg/4ypbGTRJ

**Comment by carlosvirreira** [comment]
hey @ap172x how is it going with this issue? have you made some progress?

**Comment by Hitesh-sisara** [comment]
should i give it try ? 
/attempt #309

**Comment by carlosvirreira** [comment]
hi @Hitesh-sisara we have not gotten many updates from @ap172x so you can absolutely try it and if we approve your PR you get the bounty reward!

**Comment by Hitesh-sisara** [comment]
<img width="495" alt="Screenshot 2023-09-14 at 1 59 06 PM" src="https://github.com/Shelf-nu/shelf.nu/assets/72780174/38c241e9-0dbf-4fd5-bc0c-ee32c50de43c">

i have added QR code button in header for mobile site, i need more details about what exact actions should triggred based on QR code's content

**Comment by jurrejansen** [comment]
Thank you @Hitesh-sisara 

STYLING

Would be good to have the icons horizontally aligned to the center and in the correct color. Ill add the file + color code just in case

[qr-code-01.svg.zip](https://github.com/Shelf-nu/shelf.nu/files/12606846/qr-code-01.svg.zip)

#667085

![Screenshot 2023-09-14 at 10 51 08](https://github.com/Shelf-nu/shelf.nu/assets/76112272/88a700ec-2035-474c-b801-448ae969dac8)


FUNCTIONALITY

For the sake of simplicity we want the triggered action to be: Open default camera app of the OS

Both iOS and Android have default camera apps that are capable of scanning QR codes and providing a link. That should be all you'll have to do because when a user scans a code that is part of a Shelf environment, after triggering the camera app via the icon, they'll land on the asset page. That functionality already exists.

Let me know if you have further questions :)

**Comment by DonKoko** [comment]
@Hitesh-sisara I think once you are done with the visuals, its good for you to join our discord so i can explain to you in a bit more detail the technical part as we have 2 options and there are some confusions. I want to make sure I explain exactly what we expect so you dont have to do double work. We should be working on option 1 which embeds the camera within the app, doesnt just send you to the camera app itself. You can see the video example uploaded above by Carlos.

**Comment by Hitesh-sisara** [comment]
my Discord usename : hitesh_techhiyo

**Comment by carlosvirreira** [comment]
> my Discord usename : hitesh_techhiyo

Join us here please > https://discord.gg/2fNUw7DT

**Comment by DonKoko** [comment]
There is still some stuff pending here but I am closing it and leaving it as debt for the future.
