### ISSUE TITLE
[Bug]: Cannot update image of locations

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#401]
### What happened?

username: carlos

Try to change the picture of one of my locations. I end up getting an error.

https://github.com/Shelf-nu/shelf.nu/assets/12449255/7017796a-59ae-4afe-81bf-9ab82f796b28

### What is the expected behaviour?

New picture gets shown. 

I thought it had to do with the way my picture file name was formatted. I changed it and it still gives an error.

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Safari

**Comment by imVinayPandya** [comment]
Hey @DonKoko 
After hours of debugging i found that data is bing change in database, only problem is that image is being cached.

Try your self:
- Try to update image and location title from edit page
- click on update button 
- click on location from sidebar
- you will see name is updated but image it not updated on location list page.

When we return the location api result, we need make sure that it should return updated data always.

**Comment by imVinayPandya** [comment]
Small update I found that the image is being cached on browser side , following trick make browser to fetch latest image.

<img width="754" alt="Screenshot 2023-10-01 at 2 41 05 PM" src="https://github.com/Shelf-nu/shelf.nu/assets/5011197/6ec9eb45-624a-474a-a9ae-40f05b1c3dd2">

cons:
- Image is loading chunks. And that can be fixed by introducing lazyloading of image.

hope this helps.

**Comment by DonKoko** [comment]
hey @imVinayPandya you are correct. I figured that out as well, that the image gets cached and refreshing the page without cache actually works.
So i think your suggestion is good. So one thing tho, this will prevent the image from ever being cached, because it always takes Date.now, right? What we want to do is to only cache it when it hasnt been changed. Maybe we just use the `image.updatedAt` to handle that?

Also I think you already put all the work so it would be lovely if you make a PR for it.

**Comment by imVinayPandya** [comment]
Hey @DonKoko 
I am very new to this repo. I just barely spend 1-2 hours to explore this issue. Also I am very knew to remix as well. I have submitted the MR, feel free to add sugession/comment.

Though I have another solution for this issue. Instead of using image's updatedAt date, we can use location's updatedAt date. 

### Pros:
- Doing that we will not have to make join query
- Avoid joins, it will not effect the api reponse or page load time on client side

### Cons:
- Even though image is not updated, we might endup telling browser to re-fetch image (I guess which is fine)

wdyt?

**Comment by DonKoko** [comment]
@imVinayPandya i checked your PR and that was good enough already. I am not worried about the joins because those are small queries.

**Comment by imVinayPandya** [comment]
Nice @DonKoko , Thank you.
