### ISSUE TITLE
[Feature request]: Positioning of submit/save button

### ISSUE THREAD

**Issue by hunar1312** [Shelf-nu/shelf.nu#663]
### Is your feature request related to a problem? Please describe?

The save/submit button on edit/new pages of modules is currently placed at the bottom where form ends which leads to bad UX on edit routes as you have to scroll long.

### Describe the solution you'd like

The submit/save button should be placed on top of form.

### Additional context

referenced from user request mentioned [here](https://github.com/orgs/Shelf-nu/discussions/639#discussion-6029622)

**Comment by jurrejansen** [comment]
@hunar1312 @DonKoko For sure, I guess this changed together with the UI changes. Best case Action buttons are placed like in the scenario. But I am not sure if it that simple to do.

https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=128-233469&mode=design

**Comment by DonKoko** [comment]
Okey so I reviewed the designs and I think there are still some stuff that we need to discuss internally.
@rockingrohit9639 if you want to help with this, we can already start with the most important part, which will also solve the issue with the chat bubble from #785. 

What I would like to do is add the action buttons on the header on the new & edit views of the following models:
- [ ] Asset
- [ ] Location

In terms of technical implementation it can be a bit tricky because of the structure of the layout so you need to absolutely position the buttons. You can check as an example how we did it with bookings, as we already have those buttons there.
What buttons:
- [ ] Save
- [ ] Add another - link to `/new`
- [ ] Cancel - just a link to the prev page

<img width="751" alt="Screenshot 2024-02-27 at 13 11 51" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/3c64d6c4-818f-443d-8329-7ba9a90f60d0">

@rockingrohit9639 is that something you could work on?

**Comment by DonKoko** [comment]
Perfect. Assigning to you.

**Comment by DonKoko** [comment]
@jurrejansen @carlosvirreira deploying to testapp. Pls test and lmk what is your feedback. 
https://github.com/Shelf-nu/shelf.nu/actions/runs/8191642120
