### ISSUE TITLE
[Feature request]: Improve adding to booking flow

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#768]
### Is your feature request related to a problem? Please describe?

(Reported by a set of users)

- The most confusing part of the booking process is adding assets. As one has to toggle buttons and nothing happens in the back-end. It makes the user spend time scrolling through the modal to find no 'save' 'add' or 'complete' action. 
- Modal has to be closed for the action to be performed. On mobile this is even more confusion.

### Describe the solution you'd like

Ideally a better CTA to add the items or a notice on the page that reads something like 'Clicking on an asset will add it to the booking/reservation - when you close the popup all those assets will be shown there'

Or something similar.

**Comment by jurrejansen** [comment]
@DonKoko @carlosvirreira designs look like this
![Screenshot 2024-02-20 at 14 17 39](https://github.com/Shelf-nu/shelf.nu/assets/76112272/2a18ad30-5b97-43ea-80fa-96bb6ec30c8d)

https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=14-50739&mode=design

**Comment by DonKoko** [comment]
Yes thats my bad. I thought the implementation I did was cleaner when building it and easier, but will completely change how it works. I think this will be easier for the user.

**Comment by jurrejansen** [comment]
@DonKoko Not sure if "but will completely change how it works" means you're going to fully / partially re-do the component or anything but there are few improvements reported here and there. As we're also using a similar component for handling 'adding/removing' assets for Locations, and probably going to use it in other places in the future.

- Sticky header + footer
- Adding all or some filters
![Screenshot 2024-02-20 at 14 35 27](https://github.com/Shelf-nu/shelf.nu/assets/76112272/ad7e4a98-3799-4c7c-b384-4d77bd59ed92)
- Making rows clickable for adding / removing instead of having to click checkbox

I presume this is already, or should be a re-usable component for managing assets. If u think it's worth we can take a look at the latest designs and make it as re-usable as can be.

**Comment by DonKoko** [comment]
Yea its a complete rebuild due to a few reasons:
- Need to differently structure the html of the modal
- Need to disabled the submitting of data on check and only send all the data when clicking done

So it might look the same but the way it will work will be very different. Also selecting multiple assets with pagination across multiple pages is kind of a nightmare. Very tricky to do.

**Comment by jurrejansen** [comment]
@DonKoko I see, in that case it would be nice to review the latest designs together somewhere before you start working on it. Just let me know when it's coming up.

I already prepped a UX without pagination so that's good
![Screenshot 2024-02-20 at 15 21 18](https://github.com/Shelf-nu/shelf.nu/assets/76112272/082344b4-661c-4b9c-b81f-1d26589e1661)

**Comment by DonKoko** [comment]
@jurrejansen thanks bro. That doesn't change much tho, this is still basically pagination, just works different. Anyways, I think I have found a way to make it work kinda with our current lists that will be for sure better than what we have now. I will make some updates and share.

**Comment by DonKoko** [comment]
> Sticky header + footer

Done

> Making rows clickable for adding / removing instead of having to click checkbox

Done.


I have also completely changed how it works. Clicking the items won't add/remove them anymore, it will just keep a list and once you click confirm, the action will be executed.
