### ISSUE TITLE
[Feature request]: Asset actions on asset index

### ISSUE THREAD

**Issue by apvlv** [Shelf-nu/shelf.nu#871]
### Contact Details

andrej@twinbrothers.film

### Is your feature request related to a problem? Please describe?

As a user i want to execute quick common actions without navigating forth and back

### Describe the solution you'd like

E.g. each item row has quick action icons for "Update Location", "Add to Booking", "Show item info"

**Comment by carlosvirreira** [comment]
I think we had a concept for this - right @jurrejansen ? 

I remember we had discussed/seen such a concept before.

**Comment by jurrejansen** [comment]
@DonKoko @carlosvirreira I think it would be best to add the Actions icon in every row in the asset index. This opens the same Actions menu that would open if you would click Actions on the asset page. Would be good to have a 'View' option in the dropdown if activated on the index though, so that would be a difference.

Depending on the action chosen it just opens the relevant modal on the index page. Here's a scenario that shows how updating a location would work.

https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=4523-13332&mode=design

We already have this pattern on a few other indexes. However, it looks / behaves a little bit different at every place it is implemented.


THINGS TO KEEP IN MIND

Place the icon in a container / link block to have a bigger and easier to click area.

https://github.com/Shelf-nu/shelf.nu/assets/76112272/3487ca4e-364e-428a-9ca3-b04581efdac3
![Screenshot 2024-03-26 at 10 30 49](https://github.com/Shelf-nu/shelf.nu/assets/76112272/ab5bd2fc-5c4a-4b5a-8f9d-396d63b1920b)

No need for table header text
![Screenshot 2024-03-26 at 10 34 00](https://github.com/Shelf-nu/shelf.nu/assets/76112272/23883418-9cd3-4054-a771-9e9811ea123f)

Lets try to keep the width of this extra column as low as possible so it doesn't eat up too much screen real estate

**Comment by DonKoko** [comment]
I like this. We already have a component for it so it should be quite straightforward to implement. @apvlv is that what you had in mind?

**Comment by apvlv** [comment]
Yeah, would be totally fine for me. As long as I don't have to go into item detail view every time, all is fine :)

**Comment by apvlv** [comment]
and we should keep in mind that we need a multiselect feature sometime where the actions on multiple items come in place :)

**Comment by DonKoko** [comment]
Yes, we have it planned. We are however still a very small team so we try to prioritize the most requested and higher prio features.

**Comment by carlosvirreira** [comment]
@DonKoko maybe a bounty?

**Comment by DonKoko** [comment]
The bulk actions pretty much solve this case for now so I will close this issue. More actions will come with time.
