### ISSUE TITLE
[Improvement request]: Fix icons used in menu items for dropdown menu's

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#925]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

We're not consistently using a container for the icons used in menu items which results in the icons looking off. It's not something that is very high impact but it doesn't look very professional.

EXAMPLE:

![Screenshot 2024-04-23 at 17 38 54](https://github.com/Shelf-nu/shelf.nu/assets/76112272/a9678b23-907a-4862-abd6-153cbecca8a5)
![Screenshot 2024-04-23 at 17 41 56](https://github.com/Shelf-nu/shelf.nu/assets/76112272/f4404ad6-da2e-4ff6-a931-756a33adffeb)

### Describe the solution you'd like

Identify all places within the app where these dropdown menus are used and giving the icons a consistent container. Maybe there is way to create a global component for it so from now on it can stay consistent.

**Comment by DonKoko** [comment]
Okey so we need to do a wrapper of the icons inside the `Button` component as well as a helper wrapper to be used when icons are used without a `<Button>`.
That wrapper should be 20x20px and have the icon centered inside it. We already have a component called `IconHug` that was supposed to do this but it was kind of an overkill and not needed so much complexity. This component is not being used anywhere so it can be re-used for this purpose.

Another option which i think could actually be better, is coming up with some clever way to wrap all icons inside the icon library we have with the IconHug when we export them. It has to be possible to be turned off, because we have some cases where we dont need the icon hug. Its rare but it happens.

**Comment by Bhavyajain21** [comment]
can I be assigned?

**Comment by DonKoko** [comment]
@Bhavyajain21 yes no problem. Please use the algora instructions and make an attempt, then I can assign the issue to you. I also recommend you join our discord so you can directly ask me questions if you have any.

**Comment by Bhavyajain21** [comment]
please assign @DonKoko

**Comment by Bhavyajain21** [comment]
Thanks for assigning @DonKoko

**Comment by DonKoko** [comment]
@jurrejansen this is merged and being deployed to live directly. All icons are now wrapped in a 20x20px div. Of course we also have the option to turn it off for some exception cases.

Keep in mind that we have some icons where the icon itself exported from figma was wider or higher than 20px. Its usually just 1 or 2 pixels. If we notice it creating a broken UI, we can always update those icon svgs one by one.
