### ISSUE TITLE
[Feature request]: Generating a PDF with booking overview

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#942]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

"Option to print out the generated list of assets as a PDF for record keeping and for a physical reference on set."

### Describe the solution you'd like

Add a menu item under Actions called 'Generate PDF...' which will download a PDF with an overview of the booking. There's not really a reason to not let users download the PDF when the booking is in Draft but I feel we should only allow it when booking reaches Reserved.

- Workspace logo (if uploaded and workspace is Plus or Team)
- Generation date
- Workspace name
- Title (with booking name)
- Booking name
- Custodian
- Booking period
- Table with included assets (number, thumbnail, name, category, location, QR, checkbox)

SCENARIO
https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=4918-566890&mode=design

**Comment by carlosvirreira** [comment]
This seems quite ready to assign. Do you have any comments?

**Comment by DonKoko** [comment]
Okey, here are some ideas based on some research I did. 
So as always with remix, we can use a resource route, which is amazing. Here is an example from Sergio: https://sergiodxa.com/tutorials/generate-a-pdf-in-remix-with-resource-routes
Also I like that he uses this react pdf approach. I think this could be so easy to do and we can create a route in the admin dashboard so we can preview it.

Moreover this is a more general article with a lot of different libraries. They all look interesting in case we want to use one of them instead of `react-pdf`. https://dev.to/handdot/generate-a-pdf-in-js-summary-and-comparison-of-libraries-3k0p

**Comment by carlosvirreira** [comment]
Thank you for the research it sounds promising. What can we do to get this moving? The design is ready - is this a bounty-able-feat?

**Comment by jurrejansen** [comment]
@DonKoko processed feedback from user. They asked for including the asset thumbnail. Also I have changed the logo in top left to 1:1. Updated the original message with these things.

**Comment by MohakBajaj** [comment]
Sorry! I'll be withdrawing from this issue. I'm unable to find time to work on it.

**Comment by rajeshj11** [comment]
@jurrejansen please review the demo and PR changes. Please Let me know if any changes are needed.
