### ISSUE TITLE
[Bug]: Booking info in automated mail always shows info that was initially filled if you don't save before clicking Reserve

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#962]
### Contact Details

jurre@shelf.nu

### What happened?

Steps to reproduce:

1. Create a booking and Draft booking gets created
2. Adjust Name, Booking period, Custodian
3. Click Reserve
4. Booking info shows updated adjustments in Name, Booking period, Custodian
5. Automated confirmation mails still shows old Name, Booking period, Custodian

https://github.com/Shelf-nu/shelf.nu/assets/76112272/f22c1e4f-509b-4d1f-b431-1596a68c5da8

### What is the expected behaviour?

Clicking Save before clicking Reserve makes it so that the automated mail uses the updated information. I would say by clicking Reserve the system should perform a Save action making sure the info in the updated mail is showing the updated booking info.

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome

**Comment by DonKoko** [comment]
Because of how we built this initially and we changed it after, we basically have to completely refactor the server code to make this work. I have looked at it and I see 2 options:
1. Keeping the same UI and buttons and actions and make every action save the update data. So it will be 100% like its now, it will just work different on the server
2. Making it so changing any field in the left side, automatically saves the data. Then we can drop the save button and we will know the data is always(unless failure but we handle errors so it shouldn't be an issue) up to date. I think in that case we need to add some text "changes saved" or something like this. 

Considering that both options require a lot of work and there is no easy option, I think we should decide whatever is the best UX and focus on giving that to our users.

**Comment by carlosvirreira** [comment]
I wrote this on Discord but let me put it here. 

If this behavior affects one or two flows - I would opt then to propose option 3:

Show users a warning - changes detected, please save them. 

As a lower implementation time/effort option that could yield the same results. Changing our Save button or how each field works feels like a lot of work to me.
